export const drugs = [
  'Abacavir',
  'Abacavir + Lamivudine',
  'Abacavir + Lamivudine + Zidovudine',
  'Abatacept',
  'Abciximab',
  'Abiraterone',
  'Acamprosate',
  'Acarbose',
  'Acebutolol',
  'Aceclofenac',
  'Acemetacin',
  'Acenocoumarol',
  'Acetazolamide',
  'Acetylcholine',
  'Acetylcysteine',
  'Aciclovir',
  'Acipimox',
  'Acitretin',
  'Aclarubicin',
  'Acrivastine',
  'Acrivastine + Pseudoephedrine',
  'Adalimumab',
  'Adapalene',
  'Adefovir',
  'Adenosine',
  'Afatinib',
  'Aflibercept',
  'Agalsidase beta',
  'Agomelatine',
  'Ajmaline',
  'Albendazole',
  'Alclofenac',
  'Alclometasone',
  'Alcohol',
  'Alcuronium',
  'Aldesleukin',
  'Alemtuzumab',
  'Alendronic acid',
  'Alendronic acid + Colecalciferol',
  'Alfacalcidol',
  'Bacampicillin',
  'Bacillus clausii',
  'Bacitracin',
  'Bacitracin + Polymyxin B',
  'Baclofen',
  'Balsalazide',
  'Bambuterol',
  'Bamifylline',
  'Bamipine',
  'Baricitinib',
  'Barnidipine',
  'Basiliximab',
  'Batroxobin',
  'Beclometasone',
  'Bedaquiline',
  'Belimumab',
  'Belladonna',
  'Benazepril',
  'Bencyclane',
  'Bendamustine',
  'Bendroflumethiazide',
  'Benfluorex',
  'Benfotiamine',
  'Benidipine',
  'Benorilate',
  'Benserazide + Levodopa',
  'Benzalkonium chloride',
  'Benzathine benzylpenicillin',
  'Benzatropine',
  'Benzbromarone',
  'Benzocaine',
  'Benzoxonium chloride',
  'Benzoyl peroxide',
  'Benzydamine',
  'Benzyl benzoate',
  'Benzylpenicillin',
  'Benzylthiouracil',
  'Bepridil',
  'Beractant',
  'Beraprost',
  'Cabergoline',
  'Cabozantinib',
  'Caffeine',
  'Calamine',
  'Calcipotriol',
  'Calcitonin',
  'Calcitriol',
  'Calcium acetate',
  'Calcium carbonate',
  'Calcium carbonate + Vitamin D3',
  'Calcium chloride',
  'Calcium citrate + Vitamin D3',
  'Calcium dobesilate',
  'Calcium folinate',
  'Calcium gluconate',
  'Calcium lactate',
  'Calcium phosphate',
  'Calfactant',
  'Camostat',
  'Camylofin',
  'Canagliflozin',
  'Canakinumab',
  'Candesartan',
  'Candesartan + Hydrochlorothiazide',
  'Canrenone',
  'Capecitabine',
  'Capreomycin',
  'Captodiame',
  'Captopril',
  'Captopril + Hydrochlorothiazide',
  'Carbachol',
  'Carbamazepine',
  'Carbazochrome',
  'Carbenicillin',
  'Carbenoxolone',
  'Carbetocin',
  'Carbidopa + Levodopa',
  'Carbidopa + Levodopa + Entacapone',
  'Carbimazole',
  'Carbinoxamine',
]